config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :users

  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :tasks, only: %i[index show create edit update destroy] do
    member do
      post '/pomodoros', to: 'pomodoro_timer#create'
      get '/timer', to: 'pomodoro_timer#timer'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pomodoro.rb
class Pomodoro < ApplicationRecord
  belongs_to :user
  belongs_to :task

end

app/models/task.rb
class Task < ApplicationRecord

  validates :content, presence: true, length: { maximum: 50 }

  belongs_to :user
  has_many :pomodoros, dependent: :nullify
  enum state: { todo: 0, doing: 1, done: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 5}, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password]}

  validates :email, uniqueness: true

  has_many :pomodoros, dependent: :destroy
  has_many :tasks, dependent: :nullify

  enum role: { general: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :info, :warning, :danger

private

  def not_authenticated
    redirect_to login_path, alert: 'ログインしてください'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_action :require_login

  def index; end
end

app/controllers/pomodoro_timer_controller.rb
class PomodoroTimerController < ApplicationController
  def timer
    @pomodoro = Pomodoro.new
    @task = Task.find(params[:id])
    session[:task_id] = @task.id
  end

  def create
    @pomodoro = Pomodoro.new(pomodoro_params)
    @pomodoro.save
    redirect_to tasks_path, success: 'ポモドーロ回数を更新しました！'
  end

private

  def pomodoro_params
    params.require(:pomodoro).permit(:user_id, :task_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks
  end

  def show
    @task = Task.find(params[:id])
    @data = []
    d = Time.zone.today
    pomodoros = @task.pomodoros.group("date(created_at)").count
    (0..6).each do |a|
      @data.push([d - a, pomodoros[d - a]])
    end
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path, success: 'タスク登録しました'
    else
      redirect_to tasks_path, danger: 'タスク作成に失敗しました'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.new(task_params)
    @task.update!
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy!
    redirect_to tasks_path, success: 'タスクを削除しました'
  end

private

  def task_params
    params.permit(:content, :deadline).merge(user_id: current_user.id)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to tasks_path, success: 'ログインしました。'
    else
      render :new
      flash.now[:danger] = 'ログインに失敗しました。'
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_login, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def show
    @user = current_user
    @data = []
    d = Time.zone.today
    pomodoros = current_user.pomodoros.group("date(created_at)").count
    (0..6).each do |a|
      @data.push([d - a, pomodoros[d - a]])
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: 'ユーザー登録が完了しました。お手数ですがログインをお願い致します。'
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pomodoro_timer_helper.rb
module PomodoroTimerHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= javascript_pack_tag 'hello_vue' %>
<%= stylesheet_pack_tag 'hello_vue' %>

<div id='hello'>
  {{message}}
  <app></app>
  <div class='top-wrapper'>
    <div class='top-inner-text'>
      <h1>ポモドーロで時間管理を始めよう</h1>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PomodoroTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message'%>
    <div class='container'>
      <%= yield %>
    </div>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/pomodoro_timer/timer.html.erb
<div class="timer">
    <span id="minute">25</span>：
    <span id="second">00</span>
  <br>
  <%= link_to '中断', tasks_path, id: "stp-btn", class: "btn pink" %>
  <%= form_with model: @pomodoro, url: pomodoros_task_path(@task), id: "comp-btn", local: true do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :task_id, value: @task.id %>
    <%= f.submit '完了', class: "btn", style: "background-color:#11698e; color:#eff8ff;" %>
  <% end %>
  <p style="color: red; font-size: 20px;">※ ページ遷移するとタイマーが止まるのでご注意ください！</p>
</div>
<script>
  $(function(){

  $('#comp-btn').hide();
  $('.navbar').hide();
  $('.footer').hide();
  var timer1;

    $(window).on('load', function() {
      timer1 = setInterval(function(){
        localStorage.pomo = 'pre'
        countDown()
      }, 1000);
    });

    function countDown() {
      if(localStorage.getItem('min') && localStorage.getItem('sec')){
        var min = parseInt(localStorage.getItem('min'));
        var sec = parseInt(localStorage.getItem('sec'));
      } else {
        var min = parseInt($('#minute').text());
        var sec = parseInt($('#second').text());
      };
      tmWrite(min * 60 + sec - 1);
    };

    function tmWrite(int) {
      int = parseInt(int);
      if(int <= -1) {
        clearInterval(timer1);
        $('#stp-btn').hide();
        $('#comp-btn').show();
        localStorage.count = "<%= timer_task_path(@task)%>"
        localStorage.removeItem('min');
        localStorage.removeItem('sec');
        $.removeCookie('task');
      } else {
        $('#minute').text(addZero(Math.floor(int/60)));
        $('#second').text(addZero(int % 60));
        localStorage.min = $('#minute').text();
        localStorage.sec = $('#second').text();
      };
    };

    function addZero(val) {
      if(val < 10) {
        val = '0' + val;
      }
      return val;
    }
  });
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer pt-4 my-md-5 pt-md-5 border-top'>
  <div class="container">
    <p>
      <%= link_to '利用規約', '#'%>
    </p>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="navbar shadow-sm" style="background-color:#ffe5b9;">
  <%= link_to 'PomodoroTodo', root_path, class: 'navbar-brand d-flex align-items-center title' %>
  <div class='float-light'>
    <% if current_user %>
    <div class="btn-group dropleft">
      <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Menu
      </button>
      <div class="dropdown-menu">
        <%= link_to 'やることリスト', tasks_path, class: 'dropdown-item'%>
        <%= link_to 'ユーザーページ', user_path(current_user), class: 'dropdown-item'%>
        <div class="dropdown-divider"></div>
        <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
    <% else %>
      <%= link_to '新規登録', new_user_path %>
      |
      <%= link_to 'ログイン', login_path %>
    <% end %>
  </div>
</div>

<script>

</script>

app/views/tasks/_task.html.erb
<tr id="task-<%= task.id%>">
  <th><%= check_box_tag :task %></th>
  <td><%= link_to task.content, task_path(task) %></td>
  <td><%= task.deadline %></td>
  <td><%= task.pomodoros.count %>回</td>
  <td><%= task.pomodoros.where(created_at: Time.zone.now.all_day).count%>回</td>
  <td><%= link_to 'スタート', timer_task_path(task), class: 'btn lavender start-btn'%></td>
  <td><%= link_to '編集', edit_task_path(task), class: 'btn', style: 'background-color:#bee5d3;' %></td>
  <td><%= link_to '削除', task_path(task), method: :delete, class: 'btn pink', data: { confirm: "タスクを削除しますか？" } %></td>
  <td></td>
</tr>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

      <%= form_with model: @task, local: true do |f|%>
          <div class="form-group">
            <%= f.label :content, Task.human_attribute_name(:content) %>
            <%= f.text_field :content, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :deadline, Task.human_attribute_name(:deadline) %>
            <%= f.date_field :deadline, class: 'form-control date-picker' %>
          </div>
          <%= f.submit 'タスク更新', class: 'btn green' %>
      <% end %>

app/views/tasks/index.html.erb
<div id="break-timer" style="display:none;">
<span>休憩時間</span>
<span id="break-minute">05</span>:
<span id="break-second">00</span>
<p style="color: red; font-size: 20px;">※ ページ遷移するとタイマーが止まるのでご注意ください！</p>
</div>

<div id="message"></div>

<div>
  <p class="pink" style="text-align: center; font-size: 60px;">本日の実績 <%= current_user.pomodoros.where(created_at: Time.zone.now.all_day).count%>回</p>
</div>
<h1>やることリスト</h1>

<!-- タスク新規作成モーダルボタン -->
<button type="button" class="btn lavender" data-toggle="modal" data-target="#exampleModalCenter">タスク新規作成</button>

<!-- 新規作成モーダル -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document" >
    <div class="modal-content" style="background-color:#eff8ff;">
      <div class="modal-header lavender">
        <h5 class="modal-title" id="exampleModalCenterTitle">タスク新規作成</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: @task, local: true do |f|%>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :content, Task.human_attribute_name(:content) %>
            <%= f.text_field :content, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :deadline, Task.human_attribute_name(:deadline) %>
            <%= f.date_field :deadline, class: 'form-control date-picker' %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit 'タスク登録', class: 'btn green' %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<table class='table js-table-task' style="background-color:white;">
  <thead>
    <tr>
      <th></th>
      <th><%= Task.human_attribute_name(:content) %></th>
      <th><%= Task.human_attribute_name(:deadline) %></th>
      <th>合計ポモドーロ数</th>
      <th>本日のポモドーロ数</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @tasks.present?%>
    <%= render @tasks %>
    <% else %>
    <td>タスクがありません</td>
    <% end %>
  </tbody>
</table>

<script>
  $(function(){

    if(localStorage.getItem('pomo')){
      $('.start-btn').show();
    };
    
    var timer1;
    if(localStorage.getItem('count')){
      $('#break-timer').show();
      $('.start-btn').hide();
      $(window).on('load', function() {
        timer1 = setInterval(function(){
          breakCountDown()
        }, 1000);
      });
    };

    function breakCountDown() {
      if(localStorage.getItem('breakMin') && localStorage.getItem('breakSec')){
        var min = parseInt(localStorage.getItem('breakMin'));
        var sec = parseInt(localStorage.getItem('breakSec'));
      } else {
        var min = parseInt($('#break-minute').text());
        var sec = parseInt($('#break-second').text());
      };
      breakTmWrite(min * 60 + sec - 1);
    };

    function breakTmWrite(int) {
      int = parseInt(int);
      if(int <= -1) {
        clearInterval(timer1);
        localStorage.clear();
        $('#break-timer').hide();
        $('.start-btn').show();
      } else {
        $('#break-minute').text(addZero(Math.floor(int/60)));
        $('#break-second').text(addZero(int % 60));
        localStorage.breakMin = $('#break-minute').text();
        localStorage.breakSec = $('#break-second').text();
      };
    };

    function addZero(val) {
      if(val < 10) {
        val = '0' + val;
      }
      return val;
    }
  });
</script>

app/views/tasks/show.html.erb
<h1>タスク詳細ページ</h1>
<div class="text-right">
  <%= link_to '編集', edit_task_path(@task), class: 'btn btn-info' %>
</div>

<table class="table" style="background-color: white;">
  <tr>
    <th scope="row"><%= Task.human_attribute_name(:content) %></th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th scope="row"><%= Task.human_attribute_name(:deadline) %></th>
    <td><%= @task.deadline %></td>
  </tr>
  <tr>
    <th scope="row">一週間の実績</th>
    <td><%= bar_chart @data, width: "800px" %></td>
  </tr>
</table>

app/views/user_sessions/new.html.erb
<h1>ログイン</h1>

<%= form_with url: login_path, method: :post, local: true do |f| %>
  <div class='form-group'>
    <%= f.label :email, User.human_attribute_name(:email) %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password, User.human_attribute_name(:password) %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit 'ログイン', class: 'btn green' %>
<% end%>

<%= link_to '新規登録はこちら', new_user_path, class: '' %>
<br>
<%= link_to 'パスワードをお忘れの方はこちら', '#' %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '登録', class: 'btn green' %>
<% end%>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<table class="table" style="background-color: white;">
  <tr>
    <th scope="row"><%= User.human_attribute_name(:name) %></th>
    <td><%= current_user.name %></td>
  </tr>
  <tr>
    <th scope="row"><%= User.human_attribute_name(:email) %></th>
    <td><%= current_user.email %></td>
  </tr>
  <tr>
    <th scope="row">一週間の実績</th>
    <td><%= bar_chart @data, width: "800px" %></td>
  </tr>
</table>